
export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  ANALYSIS = 'ANALYSIS',
  PROPOSAL = 'PROPOSAL',
  CONTRACTED = 'CONTRACTED',
  LOST = 'LOST'
}

export enum UserRole {
  ADMIN = 'ADMIN',
  PARTNER = 'PARTNER'
}

export enum MembershipGrade {
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  DIAMOND = 'DIAMOND',
  PLATINUM = 'PLATINUM'
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  TRIAL = 'TRIAL',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED'
}

export interface LoginLog {
  id: string;
  userId: string;
  userName: string;
  loginId: string;
  ipAddress?: string;
  userAgent?: string;
  createdAt: string;
}

export interface User {
  id: string;
  loginId: string;
  password?: string; // Added: Password for login
  name: string;
  phone: string;
  role: UserRole;
  grade?: MembershipGrade;
  subscriptionStatus?: SubscriptionStatus;
  monthlyFee?: number;
  nextPaymentDate?: string;
  leadsCount?: number; // Added: Number of leads assigned/generated
  activeConsultationsCount?: number; // Added: Number of active consultations
  contentGenCount?: number; // Added: Number of content generations
  insuranceDesignCount?: number; // Added: Number of insurance designs
  goldenSystemCount?: number; // Added: Number of golden system executions
  revenueGenerated?: number; // Added: Revenue generated by this partner
  createdAt: string;
  isActive: boolean;
  solapiConfig?: {
    apiKey: string;
    apiSecret: string;
    pfid: string;
    senderNumber: string;
  };
  apiKeys?: {
    gemini?: string;
    openai?: string;
    resend?: string;
  };
}

export interface Lead {
  id: string;
  userId: string; // Associated partner ID
  name: string;
  phone: string;
  email?: string;
  status: LeadStatus;
  priority: 'LOW' | 'MEDIUM' | 'HIGH';
  source: string;
  notes?: string;
  formData?: Record<string, any>; // Added: Flexible form data storage
  createdAt: string;
  submittedAt?: string;
  lastContactDate?: string;
  nextFollowUpDate?: string;
  estimatedValue?: number;
}

export interface DashboardStats {
  contentGenCount: string;
  insuranceDesignCount: string;
  goldenSystemCount: string;
  totalLeads: string;
  activeConsultations: string;
  
  contentGenTrend: string;
  insuranceDesignTrend: string;
  goldenSystemTrend: string;
  totalLeadsTrend: string;
  activeConsultationsTrend: string;
}

export interface ChartDataPoint {
  name: string;
  leads: number;
  revenue: number;
}

export interface DashboardData {
  stats: DashboardStats;
  chartData: ChartDataPoint[];
}

export interface SystemSettings {
  autoApproveNewMembers: boolean;
  defaultMonthlyFee: number;
  syncDashboardWithMemberFees: boolean;
  maintenanceMode: boolean;
  naverNeighborAutoUrl?: string;
}

export interface AppNotification {
  id: string;
  type: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR';
  title: string;
  message: string;
  targetUserId?: string; // If undefined, it's for everyone
  targetUserName?: string; // For display in admin logs
  createdAt: string;
}

export interface MarketingContent {
  id: string;
  title: string;
  type: 'BLOG' | 'SHORTFORM';
  status: 'DRAFT' | 'SCHEDULED' | 'PUBLISHED';
  publishDate: string;
}

export interface CalendarEvent {
  id: string;
  userId: string;
  date: string; // YYYY-MM-DD
  title: string;
  time: string;
  content: string;
  location: string;
  memo: string;
  createdAt: string;
}

export interface KeywordRecommendation {
  keyword: string;
  category: string;
  type: string;
  intent: string;
  competition: string;
  searchVolume: string;
  seasonality: string;
  profitability: string;
  ageSuitability: string;
  googlePopularity: string;
  naverPopularity: string;
  daumPopularity: string;
}

export interface GoldenKeywordState {
  category: string;
  topic: string;
  persona: string;
  keywordRecommendations: KeywordRecommendation[];
  selectedKeywords: string[];
  editedKeywords: string[];
  longtailKeywordRecommendations: string[];
  selectedLongtailKeywords: string[];
  editedLongtailKeywords: string[];
  titleRecommendations: string[];
  selectedTitle: string;
  editedTitle: string;
  toneStyle: string;
  generatedPost: {
    title: string;
    content: string;
    hashtags: string[];
  } | null;
  editedPost: {
    title: string;
    content: string;
  } | null;
  htmlVersion: string;
  markdownVersion: string;
  imageAssets: string[];
  currentStep: number;
  savedDraft: boolean;
  finalConfirmed: boolean;
  isAutoGenerating: boolean;
}
